BEGIN;
CREATE TABLE IF NOT EXISTS reported_financials_v1 (
    ticker text,
    composite_figi text,
    event_date date,
    report_date date,
    updated_date date,
    period text,
    accumulated_other_comprehensive_income bigint,
    accumulated_retained_earnings_deficit bigint,
    asset_turnover bigint,
    assets bigint,
    assets_average bigint,
    assets_current bigint,
    assets_non_current bigint,
    average_equity bigint,
    book_value_per_share numeric(18, 4),
    capital_expenditure bigint,
    cash_and_equivalents bigint,
    cash_and_equivalents_usd bigint,
    consolidated_income bigint,
    cost_of_revenue bigint,
    current_liabilities bigint,
    current_ratio numeric(18, 4),
    debt bigint,
    debt_current bigint,
    debt_non_current bigint,
    debt_to_equity_ratio numeric(18, 4),
    debt_usd bigint,
    deferred_revenue bigint,
    deposits bigint,
    depreciation_amortization_and_accretion bigint,
    dividend_yield numeric(18, 4),
    dividends_per_basic_common_share numeric(18, 4),
    earning_before_interest_taxes bigint,
    earning_before_interest_taxes_usd bigint,
    earnings_before_interest_taxes_depreciation_amortization bigint,
    earnings_before_interest_taxes_depreciation_amortization_usd bigint,
    earnings_before_tax bigint,
    earnings_per_basic_share numeric(18, 4),
    earnings_per_basic_share_usd numeric(18, 4),
    earnings_per_diluted_share numeric(18, 4),
    ebitda_margin numeric(18, 4),
    effect_of_exchange_rate_changes_on_cash bigint,
    enterprise_value bigint,
    enterprise_value_over_ebit int,
    enterprise_value_over_ebitda numeric(18, 4),
    foreign_currency_usd_exchange_rate int,
    free_cash_flow bigint,
    free_cash_flow_per_share numeric(18, 4),
    goodwill_and_intangible_assets bigint,
    gross_margin numeric(18, 4),
    gross_profit bigint,
    income_tax_expense bigint,
    interest_expense numeric(18, 4),
    inventory bigint,
    invested_capital bigint,
    invested_capital_average bigint,
    investments bigint,
    investments_current bigint,
    investments_non_current bigint,
    issuance_debt_securities bigint,
    issuance_equity_shares bigint,
    liabilities_non_current bigint,
    market_capitalization bigint,
    net_cash_flow bigint,
    net_cash_flow_business_acquisitions_disposals bigint,
    net_cash_flow_from_financing bigint,
    net_cash_flow_from_investing bigint,
    net_cash_flow_from_operations bigint,
    net_cash_flow_investment_acquisitions_disposals bigint,
    net_income bigint,
    net_income_common_stock bigint,
    net_income_common_stock_usd bigint,
    net_income_to_non_controlling_interests bigint,
    net_loss_income_from_discontinued_operations bigint,
    operating_expenses bigint,
    operating_income bigint,
    payment_dividends_other_cash_distributions bigint,
    payout_ratio numeric(18, 4),
    preferred_dividends_income_statement_impact bigint,
    price_earnings numeric(18, 4),
    price_sales numeric(18, 4),
    price_to_book_value numeric(18, 4),
    price_to_earnings_ratio numeric(18, 4),
    price_to_sales_ratio numeric(18, 4),
    profit_margin numeric(18, 4),
    property_plant_equipment_net bigint,
    research_and_development_expense bigint,
    return_on_average_assets bigint,
    return_on_average_equity bigint,
    return_on_invested_capital bigint,
    return_on_sales bigint,
    revenues bigint,
    revenues_usd bigint,
    sales_per_share numeric(18, 4),
    selling_general_and_administrative_expense bigint,
    share_based_compensation bigint,
    share_factor bigint,
    share_price_adjusted_close numeric(18, 4),
    shareholders_equity bigint,
    shareholders_equity_usd bigint,
    shares bigint,
    tangible_asset_value bigint,
    tangible_assets_book_value_per_share numeric(18, 4),
    tax_assets bigint,
    tax_liabilities bigint,
    total_liabilities bigint,
    trade_and_non_trade_payables bigint,
    trade_and_non_trade_receivables bigint,
    weighted_average_shares bigint,
    weighted_average_shares_diluted bigint,
    working_capital bigint,
    source datasource,
    PRIMARY KEY (ticker, composite_figi, report_date, period)
);
COMMIT;
