BEGIN;

DROP TYPE dimension;
DROP TABLE IF EXISTS fundamentals;

ALTER TABLE eod DROP COLUMN market_cap;
ALTER TABLE eod DROP COLUMN ev;
ALTER TABLE eod DROP COLUMN pe;
ALTER TABLE eod DROP COLUMN pb;
ALTER TABLE eod DROP COLUMN ps;
ALTER TABLE eod DROP COLUMN ev_ebit;
ALTER TABLE eod DROP COLUMN ev_ebitda;

COMMIT;