BEGIN;

CREATE TYPE dimension AS ENUM ('As-Reported-Annual', 'Most-Recent-Annual', 'As-Reported-Quarterly', 'Most-Recent-Quarterly', 'As-Reported-Trailing12', 'Most-Recent-Trailing12');

ALTER TYPE datasource ADD VALUE IF NOT EXISTS 'sharadar.com';

CREATE TABLE IF NOT EXISTS fundamentals (
    ticker TEXT,
    composite_figi TEXT,
    dim DIMENSION NOT NULL,

    cost_of_revenue BIGINT,
    total_sell_gen_admin_exp BIGINT,
    research_devel_exp BIGINT,
    opex BIGINT,
    interest_exp BIGINT,
    tax_exp BIGINT,
    net_income_discontinued_operations BIGINT,
    consolidated_income BIGINT,
    net_income_nci BIGINT,
    net_income BIGINT,
    pref_dividends BIGINT,
    eps_diluted NUMERIC,
    wavg_shares_out BIGINT,
    wavg_shares_out_diluted BIGINT,
    capx BIGINT,
    net_business_acquisitions_divestures BIGINT,
    net_invest_acquisitions_divestures BIGINT,
    free_cash_flow_per_share NUMERIC,
    net_cash_flow_from_financing BIGINT,
    total_issuance_repayment_debt BIGINT,
    total_issuance_repayment_equity BIGINT,
    common_dividends BIGINT,
    net_cash_flow_from_invest BIGINT,
    net_cash_flow_from_oper BIGINT,
    effect_of_fgn_exch_rate_on_cash NUMERIC,
    net_cash_flow BIGINT,
    stock_based_comp BIGINT,
    total_depreciation_amortization BIGINT,
    total_assets BIGINT,
    total_invest BIGINT,
    curr_invest BIGINT,
    non_curr_invest BIGINT,
    deferred_revenue BIGINT,
    total_deposits BIGINT,
    net_property_plant_equip BIGINT,
    inventory_sterm BIGINT,
    tax_assets BIGINT,
    total_receivables BIGINT,
    total_payables BIGINT,
    intangibles BIGINT,
    total_liabilities BIGINT,
    equity BIGINT,
    retained_earnings BIGINT,
    accumulated_other_comprehensive_income BIGINT,
    curr_assets BIGINT,
    non_curr_assets BIGINT,
    curr_liabilities BIGINT,
    non_curr_liabilities BIGINT,
    tax_liabilities BIGINT,
    curr_debt BIGINT,
    non_curr_debt BIGINT,
    ebt BIGINT,
    fgn_exchange_rate NUMERIC,
    equity BIGINT,
    eps NUMERIC,
    total_revenue BIGINT,
    net_income_common_stock BIGINT,
    cash_equiv BIGINT,
    book_value_per_share NUMERIC,
    total_debt BIGINT,
    ebit BIGINT,
    ebitda BIGINT,
    shares_out BIGINT,
    dividend_per_share NUMERIC,
    share_factor NUMERIC,
    market_cap BIGINT,
    ev BIGINT,
    invest_capital BIGINT,
    equity_avg BIGINT,
    assets_avg BIGINT,
    invested_capital_avg BIGINT,
    tangibles BIGINT,
    roe NUMERIC,
    roa NUMERIC,
    free_cash_flow BIGINT,
    ret_on_invested_capital NUMERIC,
    gross_profit BIGINT,
    opinc BIGINT,
    gross_margin NUMERIC,
    net_margin NUMERIC,
    ebitda_margin NUMERIC,
    return_on_sales NUMERIC,
    asset_turnover NUMERIC,
    payout_ratio NUMERIC,
    ev_to_ebitda NUMERIC,
    ev_to_ebit NUMERIC,
    pe NUMERIC,
    pe_alt NUMERIC,
    sales_per_share NUMERIC,
    price_to_sales_alt NUMERIC,
    price_to_sales NUMERIC,
    pb NUMERIC,
    debt_to_equity BIGINT,
    dividend_yield NUMERIC,
    curr_ratio NUMERIC,
    working_capital BIGINT,
    tangible_book_value_per_share NUMERIC,

    source datasource,
    created TIMESTAMP NOT NULL DEFAULT now(),
    lastchanged TIMESTAMP NOT NULL DEFAULT now()

    PRIMARY KEY (composite_figi, dim, event_date)
);

COMMIT;